# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # https://docs.vagrantup.com.

  config.vm.box = 'ubuntu/trusty64'

  config.vm.synced_folder "~/shared", "/home/vagrant/shared"

  config.vm.provider 'virtualbox' do |v|
    # use all cpus
    v.cpus = `sysctl -n hw.ncpu`.to_i
    # default memory to 4GB to handle all services
    v.memory = 4096
  end

  # so we can clone from private repositories from within the VM
  config.ssh.forward_agent = true

  # setup script
  config.vm.provision :shell, path: "bootstrap.sh"     
  
  # install docker
  config.vm.provision 'docker'

end
